version: "3.8"
services:
  postgresdb:
    container_name: postgresdb
    image: postgres:13
    env_file:
      - .env
    ports:
      - 2345:5432 # I already have a postgres running on 5432
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: on-failure

  lab:
    container_name: lab
    image: quay.io/jupyter/scipy-notebook
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: ./
        target: /home/jovyan/work
    command: >
      sh -c "pip install psycopg2-binary && jupyter lab"
    depends_on:
      - postgresdb
    restart: unless-stopped

volumes:
  postgres_data:
