services:
  magic:
    container_name: ${PROJECT_NAME}-magic
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_CODE_PATH="/home/src/${PROJECT_NAME}"
    image: mage
    env_file:
      - .env
    ports:
      - 6789:6789
    volumes:
      - type: bind
        source: ./mage
        target: /home/src/
    command: >
      mage start ${PROJECT_NAME}
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
    restart: on-failure

  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:13
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - type: volume
        source: postgres_mage
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure

volumes:
  postgres_mage:
